//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantApproval
    {
        public int ID { get; set; }
        public string PostedBy { get; set; }
        public string ApplicantID { get; set; }
        public Nullable<int> JobListID { get; set; }
        public Nullable<int> ApprovalStatu { get; set; }
        public Nullable<System.DateTime> APproveDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual JobList JobList { get; set; }
    }
}
