//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.ApplicantApprovals = new HashSet<ApplicantApproval>();
            this.ApplicantApprovals1 = new HashSet<ApplicantApproval>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.Certifications = new HashSet<Certification>();
            this.Educations = new HashSet<Education>();
            this.JobPreferences = new HashSet<JobPreference>();
            this.JobPreferences1 = new HashSet<JobPreference>();
            this.JobsApplies = new HashSet<JobsApply>();
            this.JobsApplies1 = new HashSet<JobsApply>();
            this.Passports = new HashSet<Passport>();
            this.Referees = new HashSet<Referee>();
            this.Skills = new HashSet<Skill>();
            this.UserDetails = new HashSet<UserDetail>();
            this.WorkedExpres = new HashSet<WorkedExpre>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<ApplicantApproval> ApplicantApprovals { get; set; }
        public virtual ICollection<ApplicantApproval> ApplicantApprovals1 { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Certification> Certifications { get; set; }
        public virtual ICollection<Education> Educations { get; set; }
        public virtual ICollection<JobPreference> JobPreferences { get; set; }
        public virtual ICollection<JobPreference> JobPreferences1 { get; set; }
        public virtual ICollection<JobsApply> JobsApplies { get; set; }
        public virtual ICollection<JobsApply> JobsApplies1 { get; set; }
        public virtual ICollection<Passport> Passports { get; set; }
        public virtual ICollection<Referee> Referees { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<WorkedExpre> WorkedExpres { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
