//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certification
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string NameOfTheBody { get; set; }
        public string CertficateName { get; set; }
        public Nullable<System.DateTime> DateObtained { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
