//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.JobLists = new HashSet<JobList>();
            this.States = new HashSet<State>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<JobList> JobLists { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
