//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCategory
    {
        public JobCategory()
        {
            this.JobLists = new HashSet<JobList>();
            this.JobPreferences = new HashSet<JobPreference>();
        }
    
        public int Id { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<JobList> JobLists { get; set; }
        public virtual ICollection<JobPreference> JobPreferences { get; set; }
    }
}
