//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobList
    {
        public JobList()
        {
            this.ApplicantApprovals = new HashSet<ApplicantApproval>();
            this.JobsApplies = new HashSet<JobsApply>();
        }
    
        public int Id { get; set; }
        public Nullable<int> JobCategoryID { get; set; }
        public string PostedBy { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public string CompanyName { get; set; }
        public string RequiredYearsExpreince { get; set; }
        public string DesiredCourse { get; set; }
        public string JobDetails { get; set; }
        public string JobDescription { get; set; }
        public string Salary { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<ApplicantApproval> ApplicantApprovals { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<JobsApply> JobsApplies { get; set; }
    }
}
