//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPreference
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> StateID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        public virtual State State { get; set; }
    }
}
