//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobsApply
    {
        public int Id { get; set; }
        public Nullable<int> JobListID { get; set; }
        public string PostedByID { get; set; }
        public string ApplyUserID { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual JobList JobList { get; set; }
        public virtual JobsApply JobsApplies1 { get; set; }
        public virtual JobsApply JobsApply1 { get; set; }
    }
}
