//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.JobLists = new HashSet<JobList>();
            this.JobPreferences = new HashSet<JobPreference>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Name { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<JobList> JobLists { get; set; }
        public virtual ICollection<JobPreference> JobPreferences { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
